import movhub.MovhubWebApi;
import util.FileRequest;
import util.HttpRequest;
import util.IRequest;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Library lib = new Library();
        if(lib.someLibraryMethod())
            System.out.println(new App().getGreeting());

        //IRequest req = new HttpRequest();
        IRequest req = new FileRequest();
        MovhubWebApi movhubWebApi = new MovhubWebApi(req);
        movhubWebApi.searchMovie();
    }
}
